name: plasmaflow
channels:
  - conda-forge
  - bioconda
  - r
  - defaults

dependencies:
  # Python
  - python>=3.8
  
  # Core scientific computing
  - numpy>=1.20.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  
  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  
  # Hi-C specific (bioconda)
  - cooler>=0.9.0
  - cooltools>=0.5.0
  - coolpuppy>=1.1.0
  - bioframe>=0.4.0
  - pairix>=0.3.7
  
  # R and R packages
  - r-base>=4.1.0
  - r-essentials
  - bioconductor-diffhic
  - bioconductor-interactionset
  - bioconductor-genomicranges
  - bioconductor-deseq2
  - bioconductor-edger
  - bioconductor-clusterprofiler
  - bioconductor-msigdbr
  - r-ggplot2
  - r-dplyr
  - r-tidyr
  - r-readr
  - rpy2>=3.5.0
  
  # Genomics tools
  - pybedtools>=0.9.0
  - pybigwig>=0.3.18
  - pysam>=0.19.0
  - bedtools
  - samtools
  
  # Deep learning (optional)
  - deeptools
  
  # Configuration and utilities
  - pyyaml>=6.0
  - tqdm>=4.60.0
  - click>=8.0.0
  - colorlog>=6.6.0
  
  # Data handling
  - hdf5
  - pytables>=3.7.0
  - openpyxl>=3.0.9
  - xlrd>=2.0.1
  
  # Parallel processing
  - joblib>=1.1.0
  
  # Statistical analysis
  - scikit-learn>=1.0.0
  - statsmodels>=0.13.0
  
  # Network analysis
  - networkx>=2.6.0
  
  # Development tools
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  - black>=22.0.0
  - isort>=5.10.0
  - flake8>=5.0.0
  - mypy>=0.991
  - pre-commit>=2.20.0
  
  # Documentation
  - sphinx>=5.0.0
  - sphinx_rtd_theme>=1.0.0
  - nbsphinx>=0.8.9
  
  # Jupyter
  - jupyter>=1.0.0
  - ipykernel>=6.15.0
  - ipywidgets>=8.0.0
  
  # Additional bioinformatics tools
  - peakachu  # For loop calling
  - multiqc   # For quality control reports
  
  # Pip-only packages
  - pip
  - pip:
    - multiprocessing-logging>=0.3.4
    - sphinx-autodoc-typehints>=1.19.0